
    USE AdventureWorks2019
    GO

    -- GET DATE()
    SELECT  TRY_CAST(GETDATE() AS TIME) AS [TIME],      -- RETORNA O HORÁRIO(hora, minuto e segundo)
            TRY_CAST(GETDATE() AS DATE) AS [DATE],      -- RETORNA A DATA ATUAL
            GETDATE() AS [GETDATE()],                   -- RETORNA DATA E HORA
            CURRENT_TIMESTAMP AS [CURRENT_TIMESTAMP],   -- SIMILIAR A GETDATE
            SYSDATETIME() AS [SYSDATETIME()],           -- SIMILIAR AO GETDATE, MAS COM SEGUNDOS MAIS PRECISOS
            GETUTCDATE() AS [GETUTCDATE()],             -- RETORNA O HORÁRIO UTC
            SYSUTCDATETIME() AS [SYSUTCDATETIME()],     -- SIMILAR AO GETUTCDATE, PORÉM COM SEGUNDOS MAIS PRECISOS
            SYSDATETIMEOFFSET() AS [SYSDATETIMEOFFSET()]-- SIMILIAR AO SYSUTCDATETIME E COM O VALOR UTC
            CURRENT_TIMEZONE() AS [CURRENT_TIMEZONE()]  -- APESAR DE APRESENTAR ERRO ELE FUNCIONA NO SQLSERVER, ELE RETORNA O UTC DO RELOGIO E O ZONE

    SELECT @@VERSION